Fixed: ImportError: cannot import name force_text from django.utils.encoding in django4.0 & in fields.py ugettext_lazy: import error --> change to gettext_lazy